#=================================================#
#                                                 #
#             cPractice Configuration             #
#                                                 #
#=================================================#
LICENSE: OPEN-SOURCE
# Use cPractice tablist
TABLIST_ENABLE: true
MESSAGE-REPLY-BOOLEAN: true
# Lobby Coords
ESSENTIAL_SPAWN_LOCATION: world:-9999.617585349535:100.63557196779635:245.40600562996698:180.02081:5.390071
# Default language. Currently Supported: English , Espaniol
DEFAULT_LANG: EN
MOD_MODE: true
# You can use 'MONGO' or 'MONGODB' and 'FLATFILE' or 'FILE'
# If you use the MONGO method you can get information
# from there for external things like web pages or other statistical things
SAVE_METHOD: MONGO
# Command to execute on purchase of cosmetic
PURCHASE-COSMETICS-CMD: pex user {player} setpermission cosmetics.killeffects.{effect}
# Chat formats for GLOBAL & CLAN CHAT
CHAT:
  # Global chat format
  DEFAULT_FORMAT: '{prefix} {player}&7:&r {message}'
  # Clan chat format
  CLAN_FORMAT: '&7[{clan}&7] &r{prefix}{player}&7:&r {message}'
# Match configuration
MATCH:
  # How many rounds should a bridge match last
  ROUNDS_BRIDGE: 3
  # How many rounds should a ranked sumo match last
  ROUNDS_RANKED_SUMO: 1
  # ???
  REMOVE_BLOCKS_ON_ROUND_END_BRIDGE: false
  # Remove empty potion bottles
  REMOVE_POTION_BOTTLE_ON_CONSUME: false
  # Drop items in inventory on player death
  DROP_ITEMS_ON_DEATH: false
  # Fast pot
  FAST_POTION: false
  # How many hits needed to win a boxing match
  BOXING_MAX_HITS: 100
FFA:
  # Default FFA Kit
  KIT: NoDebuff
  # FFA Safezone Coords
  SAFEZONE:
    location1: world:124.0:96.0:-1078.0:0.0:0.0
    location2: world:126.0:96.0:-1076.0:0.0:0.0

QUEUE:
  # Not sure what this is - Shifuu
  AMOUNT_PER_FIGHTS: true
  # Unranked Queue settings
  UNRANKED:
    # GUI Title
    INVENTORY_TITLE: '&9Select a Kit (Unranked)'
    # kit item color
    NAME_COLOR: DARK_BLUE
    # kit item lore
    LORE:
    - '{bars}'
    - '&9In Fighting&7: &r{in-fight}'
    - '&9In Queueing&7: &r{in-queue}'
    - '&9Winstreak: &f{winstreak}'
    - '{bars}'
  # Ranked Queue settings
  RANKED:
    # GUI Title
    INVENTORY_TITLE: '&9Select a Kit (Ranked)'
    # kit item color
    NAME_COLOR: DARK_BLUE
    # kit item lore
    LORE:
    - '{bars}'
    - '&9In Fighting&7: &r{in-fight}'
    - '&9In Queueing&7: &r{in-queue}'
    - '{bars}'

QUEUES:
  # If enabled, multi-queue menu will be enabled & Single queue items will automatically be disabled
  ENABLED: false
  # Whether empty menu slots should be filled
  PLACEHOLDER-ITEMS-ENABLED: true
  # Item used to fill empty menu slots
  PLACEHOLDER-ITEM-MATERIAL: STAINED_GLASS_PANE
  PLACEHOLDER-ITEM-DATA: 7
  # Menu title
  TITLE: '&8Queues'
  # Menu size in ROWS
  # Each row has 9 slots (0-8)
  SIZE: 3
  TYPES:
    UNRANKED:
      ENABLED: true
      NAME: '&9&lUnranked'
      SLOT: 11
      ICON: IRON_SWORD
      LORE:
      - '&8&m--------------------------------'
      - '&7Casual 1v1''s matches'
      - '&7with no loss penalty.'
      - ' '
      - '&9Click to play!'
      - '&8&m--------------------------------'
    RANKED:
      ENABLED: true
      NAME: '&9&lRanked'
      SLOT: 13
      ICON: DIAMOND_SWORD
      DATA: 0
      LORE:
      - '&8&m--------------------------------'
      - '&7Casual 1v1''s matches with'
      - '&7a ranked aspect to them. This'
      - '&7includes ELO.'
      - ' '
      - '&9Click to play!'
      - '&8&m--------------------------------'
    FFA:
      ENABLED: true
      NAME: '&9&lFFA'
      SLOT: 15
      ICON: GOLD_AXE
      DATA: 0
      LORE:
      - '&8&m--------------------------------'
      - '&7Make your way through the'
      - '&7course and beat the others!'
      - '&7The player to reach the goal wins'
      - ' '
      - '&fPlaying: &9<players>'
      - '&fKit: &9<kit>'
      - ' '
      - '&9Click to play!'
      - '&8&m--------------------------------'

# Party configuration
PARTY:
  # Default host party size limit
  DEFAULT_LIMIT: 20
  # Vip host party size limit
  VIP_LIMIT: 50

# Name-tag configuration
NAMETAGS:
  # default player color
  DEFAULT_COLOR: '%color%'
  # party member color?
  PARTY_COLOR: BLUE
  # event participants color?
  EVENT_COLOR: AQUA
  # Clan prefix
  CLAN_FORMAT: '&7[%color%%clan%&7] &r'
  # Staff prefix
  STAFF_FORMAT: '&9[Staff] %color%'

# Statistics menu configuration
STATS_MENU:
  # Menu title
  TITLE: '&9&l{player} Statistics'
  # Item name
  ITEM_NAME: '&9{kit}'
  # GUI Size (ROWS)
  SIZE: 6
  # Lore
  DESCRIPTION:
  - '{bars}'
  - '&7&oElo: &f{elo}'
  - '&7&oWins: &f{wins}'
  - '&7&oLosses: &f{losses}'
  - '{bars}'
# Points needed to win a clan tournament?
WINNING-POINTS-CLAN-TOURNAMENT: 10
