#
# You can use 'MONGO' or 'MONGODB' and 'FLATFILE' or 'FILE'
# If you use the MONGO method you can get information
# from there for external things like web pages or other statistical things
LICENSE: LICENSE-HERE
TABLIST_ENABLE: true
MESSAGE-REPLY-BOOLEAN: true
ESSENTIAL_SPAWN_LOCATION: world:-9999.617585349535:100.63557196779635:245.40600562996698:180.02081:5.390071
DEFAULT_LANG: EN
MOD_MODE: true
SAVE_METHOD: MONGO
PURCHASE-COSMETICS-CMD: pex user {player} setpermission cosmetics.killeffects.{effect}
CHAT:
  DEFAULT_FORMAT: '{prefix} {player}&7:&r {message}'
  CLAN_FORMAT: '&7[{clan}&7] &r{prefix}{player}&7:&r {message}'
MATCH:
  ROUNDS_BRIDGE: 3
  ROUNDS_RANKED_SUMO: 1
  REMOVE_BLOCKS_ON_ROUND_END_BRIDGE: false
  REMOVE_POTION_BOTTLE_ON_CONSUME: false
  DROP_ITEMS_ON_DEATH: false
  FAST_POTION: false
  BOXING_MAX_HITS: 100
FFA:
  KIT: NoDebuff
  SAFEZONE:
    location1: world:124.0:96.0:-1078.0:0.0:0.0
    location2: world:126.0:96.0:-1076.0:0.0:0.0
QUEUE:
  AMOUNT_PER_FIGHTS: true
  UNRANKED:
    INVENTORY_TITLE: '&9Select a Kit (Unranked)'
    NAME_COLOR: DARK_BLUE
    LORE:
    - '{bars}'
    - '&9In Fighting&7: &r{in-fight}'
    - '&9In Queueing&7: &r{in-queue}'
    - '&9Winstreak: &f{winstreak}'
    - '{bars}'
  RANKED:
    INVENTORY_TITLE: '&9Select a Kit (Ranked)'
    NAME_COLOR: DARK_BLUE
    LORE:
    - '{bars}'
    - '&9In Fighting&7: &r{in-fight}'
    - '&9In Queueing&7: &r{in-queue}'
    - '{bars}'
QUEUES:
  ENABLED: false
  PLACEHOLDER-ITEMS-ENABLED: true
  PLACEHOLDER-ITEM-MATERIAL: STAINED_GLASS_PANE
  PLACEHOLDER-ITEM-DATA: 7
  TITLE: '&8Queues'
  SIZE: 3
  TYPES:
    UNRANKED:
      ENABLED: true
      NAME: '&9&lUnranked'
      SLOT: 11
      ICON: IRON_SWORD
      LORE:
      - '&8&m--------------------------------'
      - '&7Casual 1v1''s matches'
      - '&7with no loss penalty.'
      - ' '
      - '&9Click to play!'
      - '&8&m--------------------------------'
    RANKED:
      ENABLED: true
      NAME: '&9&lRanked'
      SLOT: 13
      ICON: DIAMOND_SWORD
      DATA: 0
      LORE:
      - '&8&m--------------------------------'
      - '&7Casual 1v1''s matches with'
      - '&7a ranked aspect to them. This'
      - '&7includes ELO.'
      - ' '
      - '&9Click to play!'
      - '&8&m--------------------------------'
    FFA:
      ENABLED: true
      NAME: '&9&lFFA'
      SLOT: 15
      ICON: GOLD_AXE
      DATA: 0
      LORE:
      - '&8&m--------------------------------'
      - '&7Make your way through the'
      - '&7course and beat the others!'
      - '&7The player to reach the goal wins'
      - ' '
      - '&fPlaying: &9<players>'
      - '&fKit: &9<kit>'
      - ' '
      - '&9Click to play!'
      - '&8&m--------------------------------'
PARTY:
  DEFAULT_LIMIT: 20
  VIP_LIMIT: 50
NAMETAGS:
  DEFAULT_COLOR: '%color%'
  PARTY_COLOR: BLUE
  EVENT_COLOR: AQUA
  CLAN_FORMAT: '&7[%color%%clan%&7] &r'
  STAFF_FORMAT: '&9[Staff] %color%'
STATS_MENU:
  TITLE: '&9&l{player} Statistics'
  ITEM_NAME: '&9{kit}'
  SIZE: 6
  DESCRIPTION:
  - '{bars}'
  - '&7&oElo: &f{elo}'
  - '&7&oWins: &f{wins}'
  - '&7&oLosses: &f{losses}'
  - '{bars}'
WINNING-POINTS-CLAN-TOURNAMENT: 10
